---
- name: Common tasks
  hosts: all
  roles:
    - { role: common,
        tags: ['common'] }
    - { role: registry,
        tags: ['registry'] }

- name: Influx tasks
  hosts: disco/influx
  roles:
    - { role: influx,
        tags: ['influx'],
        when: enable_monitoring | bool }


- name: Monitoring agent tasks
  hosts: all
  roles:
    - { role: cadvisor,
        tags: ['cadvisor'],
        when: enable_monitoring | bool }
    - { role: collectd,
        tags: ['collectd'],
        when: enable_monitoring | bool }

- name: Grafana tasks
  hosts: disco/grafana
  roles:
    - { role: grafana,
        tags: ['grafana'],
        when: enable_monitoring | bool }

- name: Rally tasks
  hosts: disco/bench
  roles:
    - { role: rally,
        tags: ['rally'] }
        
