cadvisor:
  housekeeping_interval: 5s

g5k_role: unknown

enable_monitoring: no

# enable tc constraints when invoking tc phase
tc_enable: true
# output dir to store test validation of tc rules enforcement
tc_output_dir: /tmp

# docker images
grafana_docker_image: grafana/grafana:5.1.3
influxdb_docker_image: influxdb:1.5.3
cadvisor_docker_image: google/cadvisor:v0.30.0
