- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl

- name: Installing docker
  shell: which docker || (curl -sSL https://get.docker.com/ | sh)
