# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-8.7"

  config.vm.hostname = "enos-node"
  config.vm.network :private_network, ip: "192.168.142.127", auto_config: true
  config.vm.network :private_network, ip: "192.168.143.127", auto_config: true

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 6
    vb.memory = 8192
  end

  config.vm.synced_folder "../../../..", "/home/vagrant/enos_sources",
    owner: "vagrant",
    group: "vagrant",
    type: "rsync"

  config.vm.provision "shell", path: "../enos_deps.sh"
  config.vm.provision "shell", path: "scripts/keys.sh"
  config.vm.provision "shell", path: "scripts/motd.sh"
  config.vm.provision "shell", path: "scripts/deploy.sh", privileged: false

end
