---
- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-setuptools

- easy_install:
    name: pip
    state: latest

- name: Install docker python binding
  pip:
    name: docker

- name: Mount /run
  command: mount --make-shared /run

# Note: nscd prevents kolla-toolbox to start
# See, https://bugs.launchpad.net/kolla-ansible/+bug/1680139
- name: Stop nscd service (prevents kolla-toolbox to start)
  systemd: state=stopped name=nscd
  ignore_errors: yes

