---
- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-setuptools

- name: Install docker python binding
  pip:
    name: docker

- name: Mount /run
  command: mount --make-shared /run
