---
# This is specifix to ubuntu16.04
- name: Adding flent repository
  apt_repository:
    repo: ppa:tohojo/flent
    state: present
    update_cache: yes

- name: Make sure pip3 is available
  apt:
    name: python3-pip
    state: present

- name: Install numpy (python3)
  pip:
    name: numpy
    executable: pip3
