---
# Resetting network constraints
- name: Removing root qdisc for {{ item.device }}
  shell: "tc qdisc del dev {{ item.device }} root || true"
  with_items: "{{ ips_with_constraints[inventory_hostname].devices }}"
  when:
    - item.active
    - item.type == "ether"

- name: Preparing htf for {{ item.device }}
  shell: "tc qdisc add dev {{ item.device }} root handle 1: htb"
  with_items: "{{ ips_with_constraints[inventory_hostname].devices }}"
  when:
    - tc_enable
    - item.active
    - item.type == "ether"


- name: Add rate limit
  command: "tc class add dev {{ item.1.device }} parent 1: classid 1:{{ item.0 + 1 }} htb rate {{ item.1.rate }}"
  with_indexed_items: "{{ ips_with_constraints[inventory_hostname].tc }}"
  when:
    - tc_enable
    - item[1].source == ansible_nodename 


- name: Adding delay
  command: "tc qdisc add dev {{ item.1.device }} parent 1:{{ item.0 + 1 }} handle {{ item.0 + 10 }}: netem delay {{ item.1.delay }}"
  with_indexed_items: "{{ ips_with_constraints[inventory_hostname].tc }}"

  when:
    - tc_enable
    - item[1].source == ansible_nodename


- name: Adding filter
  command: "tc filter add dev {{ item.1.device }} parent 1: protocol ip  u32 match ip dst {{ item.1.target }} flowid 1:{{ item.0 + 1 }}"
  with_indexed_items: "{{ ips_with_constraints[inventory_hostname].tc }}"
  when:
    - tc_enable
    - item[1].source == ansible_nodename

