---
- include: "setup_flent_{{ ansible_distribution }}.yml"

- name: Installing flent/netperf
  apt:
    name: "{{ item }}"
    allow_unauthenticated: yes
  with_items:
    - flent
    - netperf

- name: Installing fping
  apt:
   name: fping
   update_cache: true

- name: Uploading the host list
  template:
    src: hosts.txt.j2
    dest: /tmp/hosts

- name: Get the latencies between all the nodes
  shell: "fping -C 5 -q -s -e -f /tmp/hosts 2>/tmp/result"

- name: Fetching the results
  fetch:
    src: /tmp/result
    dest: "/{{ tc_output_dir }}/{{ inventory_hostname }}.out"
    flat: yes

- debug: msg="flent tcp_upload -l 5 -H {{ hostvars[item]['ansible_' + network_interface ]['ipv4']['address']   }} -f stats -o /tmp/tcp_upload_{{ inventory_hostname }}_{{ item  }}.stats || true 2>/dev/null"
  when: inventory_hostname == groups.all[0]
  with_items: "{{ groups.all }}"


- name: Running flent (tcp_upload)
  shell: "flent tcp_upload -l 5 -H {{ hostvars[item]['ansible_' + network_interface ]['ipv4']['address']   }} -f stats -o /tmp/tcp_upload_{{ inventory_hostname }}_{{ item  }}.stats || true 2>/dev/null"
  when: inventory_hostname == groups.all[0]
  with_items: "{{ groups.all }}"

- debug: msg="/tmp/tcp_upload_{{ inventory_hostname }}_{{ item  }}.stats"
  when: inventory_hostname == groups.all[0]
  with_items: "{{ groups.all }}"

- name: Fetching the results
  fetch:
    src: "/tmp/tcp_upload_{{ inventory_hostname }}_{{ item  }}.stats"
    dest: "{{ tc_output_dir }}/tcp_upload_{{ inventory_hostname }}_{{ item  }}.stats"
    flat: yes
  when: inventory_hostname == groups.all[0]
  with_items: "{{ groups.all }}"
