---
- name: Testing if they are some shaker logs to collect
  stat: path=/root/shaker_home
  register: conf

- name: Make a tar of the shaker execution environment
  archive:
    path: /root/shaker_home
    dest: /root/shaker.tar.gz
  when: conf.stat.exists and conf.stat.isdir

- name: Pull back the shaker execution environment
  fetch: src=/root/shaker.tar.gz
         dest={{ backup_dir }}/{{ inventory_hostname }}-shaker.tar.gz
         flat=yes
  when: conf.stat.exists and conf.stat.isdir
