---
# This will pull the images and create /srv
- include: pull.yml

- name: Generate init script
  template:
    src: init.sh.j2
    dest: /srv/init_os/init.sh

- name: Make the init script executable
  file:
    path: /srv/init_os/init.sh
    mode: 0755

- name: Get the reference on the kolla-toolbox image
  shell: "{% raw %} docker images --format '{{ .Repository }}:{{ .Tag }}' | grep kolla-toolbox {% endraw %}"
  register: kolla_toolbox_image

# Run without detaching to get exit status, but handle errors separately (next task).
# This avoids displaying a huge error if the init script fails.
- name: Launch init in kolla_toolbox container
  docker_container:
    name: kolla_toolbox
    env: "{{ os_env }}"
    command: ["/srv/init_os/init.sh"]
    image: "{{ kolla_toolbox_image.stdout }}"
    detach: false
    volumes:
      - /srv/init_os:/srv/init_os
  ignore_errors: true
  register: docker_output

- name: Check exit status of init script
  assert:
    that: "not docker_output.failed"
    fail_msg: "Openstack init script failed"
    success_msg: "Openstack init script completed successfully"
